
import './globals.css';
import { Nav } from './components/Nav';
import Footer from "./components/Footer"
import '@rainbow-me/rainbowkit/styles.css';
import { Providers } from "./providers";
import { NextUIProviders } from './Provider/NextUIProviders';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NextUIProviders>
            <Nav />
              {children}
            <Footer />
          </NextUIProviders>
        </Providers> 
      </body>
    </html>
  )
}
